name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: false

    - name: Download TFLite Models from Original Source
      run: |
        cd app/src/main/assets/
        rm *.tflite
        curl -sL -o model_classifier_screen_v5.tflite https://github.com/Juancavr6/RegiBot/raw/main/app/app/src/main/assets/model_classifier_screen_v5.tflite
        curl -sL -o model_detector_clickable_v2.tflite https://github.com/Juancavr6/RegiBot/raw/main/app/app/src/main/assets/model_detector_clickable_v2.tflite
        curl -sL -o model_detector_encounter.tflite https://github.com/Juancavr6/RegiBot/raw/main/app/app/src/main/assets/model_detector_encounter.tflite
        curl -sL -o model_detector_map_v2.tflite https://github.com/Juancavr6/RegiBot/raw/main/app/app/src/main/assets/model_detector_map_v2.tflite
        curl -sL -o predictor.tflite https://github.com/Juancavr6/RegiBot/raw/main/app/app/src/main/assets/predictor.tflite

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: sigma-bot-apk
        path: app/build/outputs/apk/debug/app-debug.apk
